### ISSUE TITLE
Implement UTF-8 Handling

### ISSUE THREAD

**Issue by arijitAD** [status-im/nim-ws#13]

**Comment by jangko** [comment]
UTF-8 handling should be straightforward to implement.
Nim string encoding is UTF-8. so the will be no conversion if the UTF-8 text is valid.

we have two choice for UTF validator:
- Nim stdlib unicode module 
  https://github.com/nim-lang/Nim/blob/d217888e5679aff063668930bd00892c4f5cb2b3/lib/pure/unicode.nim#L166

- DFA based UTF-8 validator. http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
  I have the Nim implementation, only need to polish it
