### ISSUE TITLE
Implement WebSocket Compression

### ISSUE THREAD

**Issue by arijitAD** [status-im/nim-ws#14]

**Comment by jangko** [comment]
## Changes need for extensions and compression to work

### 1. Place to store registered extensions factory
nim-ws already have the notion of `websocket server`  when using `createServer`, but the host server itself is not well defined.
Currently we use chronos HTTP server in an awkwardly way.

   * This `host server` will store registered extension(s) factory and each instance of `websocket server` will have zero or more       extension instance that can be different from other `websocket server` instance. 
   * The order of extension chain can be different for each `websocket server` instance.
   * Each extension instance will/can have their own state, for example the compression extension will manage it own decompression buffer

### 2. API to manipulate frame header and payload

* if more than one extension is in use by a `websocket-server` and it's peer, those extensions will be executed in chained fashion. frame header and frame payload can be passed from one extension to the next and each extension can transform playload and set/reset header bit(s).

### 3. Signal the application

* Extension such as deflate compression after receiving all data and done compression should signal the application about the data already successfully de/compressed or not and the data itself. 
* We need to distinguish between each instance of websocket server/connection 
* We need to know position of the extension in the execution chain
