### ISSUE TITLE
recv big binary message in multiple frames is buggy

### ISSUE THREAD

**Issue by jangko** [status-im/nim-ws#50]
sending a binary message with size = WSDefaultFrameSize * 3.

on recv side:
- the `binary` flag is not set, should be set.
- it will trigger `invalid UTF8 sequence detected`, should not happen.
- session terminated prematurely, should not happen.

identified bug:
https://github.com/status-im/nim-ws/blob/e632202037a6620d485d535f1a8ff2361cbaf5cb/ws/session.nim#L272

that line should not be there, it should be in the `if` branch after the first frame arrived.
because if next frame come, and it is a continuation frame, the binary flag will be unset.
the correct behavior is the binary flag is set for the entire session.

unidentified bug:
but after I move the line there, other bug appears. the data not completely received.
or to be precisely, the premature session termination is still there indicating another serious bug when dealing with continuation frames.

**Comment by jangko** [comment]
this line also incorrect:

https://github.com/status-im/nim-ws/blob/e632202037a6620d485d535f1a8ff2361cbaf5cb/ws/session.nim#L71

it should be:
```Nim
let len = min(data.len - i, maxSize) 
```

**Comment by dryajov** [comment]
This is definitely a bug, if you have a chance to take a look please do, otherwise I'll probably cover it as part of #53.

**Comment by jangko** [comment]
yes I will fix it along with reading frame data in frame decoder before transfer it to extensions, because it makes compression debugging become impossible.

**Comment by dryajov** [comment]
> yes I will fix it along with reading frame data in frame decoder before transfer it to extensions, because it makes compression debugging become impossible.

We can't assume that all extensions work at message boundaries instead of frame boundaries, so frames need to be passed to extensions as they come, not after the data has been accumulated.

**Comment by jangko** [comment]
fixed by #56. close
