### ISSUE TITLE
signaling the application about message status: start, final, or cancel.

### ISSUE THREAD

**Issue by jangko** [status-im/nim-ws#52]
this issue originate from compression extension #14. but as the compression progressed and I gained more understanding of how websocket works, it become apparent this signaling mechanism not only required for compressed message but for all potentially segmented messages.

a blocker issue #50 regarding broken multiple frames message must be fixed first.

our current implementation only offer `Text` or `Binary` message signal to application using return status code.

`start/first` and `final` signal is quite easy to implement, because the information is embedded into frame. we can use status code to inform application either from return code or from querying the websocket session.

but the `cancel` signal is quite tricky, because it involve exception, need more explorations. convert the exception into status code?

another approach is we wrap the incoming message into whole ready concatenated message instead of fragments. we only need to inform application whether the message is complete or incomplete because of cancellation or disconnection.

**Comment by dryajov** [comment]
I'm not sure I follow - the application doesn't need to know when a message started or finished, it only cares about reading a buffer/message. An application level message might be comprised of many websocket level frames and messages - for example, libp2p uses websockets as a streaming protocol, even tho websockets is message/frame based. We can ofcourse have events for when frames start and end and messages are completed (i.e. fin flag set), but this is mostly internal to the implementation.

**Comment by jangko** [comment]
right, turn out I confused by the buggy behavior of our `recv`, I thought it was designed to emit fragments to application. this is probably still related to #50. closing.

**Comment by zah** [comment]
Well, ideally the library will also expose a lower-level API allowing you to handle the full spectrum of WebSocket messages.

**Comment by dryajov** [comment]
> Well, ideally the library will also expose a lower-level API allowing you to handle the full spectrum of WebSocket messages.

This is what extensions are supposed to do.
