### ISSUE TITLE
Allow extensions to hijack frame processing flow

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-ws#53]
Extensions can/should hijack the flow, as it is the case of the per message deflate as outlined here - https://datatracker.ietf.org/doc/html/rfc7692#section-6:

- Compressing implies that the message is compressed and then passed to the next extension in the chain, if per message deflate is already the last extension, then it will frame the compressed message.
- Decompressing implies buffering the message, decompressing it and then passing the body and/or frame to the next extension in the chain or, the application, if per message deflate is the last extension.

The current flow needs to be slightly modified to allow for the above behavior.

**Comment by jangko** [comment]
fixed by #56. close
